---
- hosts: qa1
  remote_user: devuser
  sudo: yes
  sudo_user: devuser 
  gather_facts: no
  tasks:
  - name: mkdir .ssh
    file: dest=/home/devuser/.ssh owner=devuser mode=0700 state=directory
  - name: add key to .ssh 
    copy: src=/home/qqq/id_rsa dest=/home/devuser/.ssh/authorized_keys mode=0644 owner=devuser force=yes
