---
- hosts: localhost 
  remote_user: root
  vars_files:
    - 'vars/main.yml'
    - 'defaults/main.yml'
  tasks:
    - include: 'tasks/main.yml'
    - include: 'tasks/copy_key.yml'
  handlers:
    - include: 'handlers/main.yml'
